export enum NutrientHeaders {
  N = 'N',
  P = 'P',
  K = 'K',
  Ca = 'Ca',
  Mg = 'Mg',
  S = 'S',
  Zn = 'Zn',
  B = 'B',
  Cu = 'Cu',
  Mn = 'Mn',
  Fe = 'Fe',
  NP = 'N/P',
  NK = 'N/K',
  NS = 'N/S',
  NB = 'N/B',
  NCu = 'N/Cu',
  PMg = 'P/Mg',
  PZn = 'P/Zn',
  KCa = 'K/Ca',
  KMg = 'K/Mg',
  KMn = 'K/Mn',
  CaMg = 'Ca/Mg',
  CaMn = 'Ca/Mn',
  FeMn = 'Fe/Mn',

  phH2O = "pH em Água",
  AlSaturation = 'Saturação por Al',
  PotentialAcidity = 'Acidez Potencial',
  OrganicMatter = 'Matéria Orgânica',
  SumBases = 'Soma de Bases',
  CTCpH7 = 'CTC',
  BasesSaturation = 'Sat. por Bases'
}
